# Generated by Django 4.1.7 on 2023-03-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_user_todo_profle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='profle',
            new_name='profile',
        ),
    ]
